/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_remotex.json.  Do not edit it directly.

#pragma once
#include "seeed_mt3620_mdb.h"

// STATUS_LED
#define STATUS_LED SEEED_MT3620_MDB_USER_LED

// PIN3_GPIO6
#define PIN3_GPIO6 SEEED_MT3620_MDB_J1_PIN3_GPIO6

// I2C_ISU1
#define I2C_MASTER SEEED_MT3620_MDB_J1J2_ISU1_I2C

// SPI_ISU0
#define SPI_MASTER SEEED_MT3620_MDB_J1_ISU0_SPI

// PWM CONTROLLER 2 channel 0 is exposed on J1 pin 5, channel 1 is exposed on J1 pin 6, channel 2 is exposed on J1 pin 7, and channel 3 is exposed on J1 pin 8. Pins for this controller are shared with SEEED_MT3620_MDB_J1_PIN5_GPIO8/GPIO26, SEEED_MT3620_MDB_J1_PIN6_GPIO9/GPIO27, SEEED_MT3620_MDB_J1_PIN7_GPIO10/28, SEEED_MT3620_MDB_J1_PIN8_GPIO11/29. If this PWM Controller is requested, none of these GPIOs can be used.
#define PWM SEEED_MT3620_MDB_PWM_CONTROLLER2

// ADC CONTROLLER 0 channel 0 is exposed on pin 1, channel 1 is exposed on pin 2, and channel 2 is exposed on pin 3. Pins for this controller are shared with SEEED_MT3620_MDB_J1_PIN1_GPIO4/GPIO41, SEEED_MT3620_MDB_J1_PIN2_GPIO5/GPIO42, and SEEED_MT3620_MDB_J1_PIN3_GPIO6/GPIO43. If this ADC controller is requested, none of these GPIOs can be used.
#define ADC SEEED_MT3620_MDB_ADC_CONTROLLER0

