/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_remotex.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk_rev2.h"

// STATUS_LED_YELLOW
#define STATUS_LED AVNET_MT3620_SK_APP_STATUS_LED_YELLOW

// USER_LED_RED
#define USER_LED_RED AVNET_MT3620_SK_USER_LED_RED

// USER_LED_GREEN
#define USER_LED_GREEN AVNET_MT3620_SK_USER_LED_GREEN

// USER_LED_BLUE
#define USER_LED_BLUE AVNET_MT3620_SK_USER_LED_BLUE

// Button B
#define BUTTON_A AVNET_MT3620_SK_USER_BUTTON_A

// Button B
#define BUTTON_B AVNET_MT3620_SK_USER_BUTTON_B

// I2C_ISU2
#define I2C_MASTER AVNET_MT3620_SK_ISU2_I2C

// SPI_ISU0
#define SPI_MASTER AVNET_MT3620_SK_ISU0_SPI

// UART_ISU1
#define UART AVNET_MT3620_SK_ISU1_UART

// PWM CONTROLLER 0: channel 0 is exposed on CLICK1 (PWM), channel 1 is exposed on: CLICK2 (PWM) and PMOD (Pin 9), channel 2 is exposed on: CLICK1 (INT), CLICK2 (INT) and PMOD (Pin 7).  Pins for this controller are shared with AVNET_MT3620_SK_GPIO0, AVNET_MT3620_SK_GPIO1 and AVNET_MT3620_SK_GPIO2. If this PWM controller is requested, none of these GPIOs can be used.
#define PWM AVNET_MT3620_SK_PWM_CONTROLLER0

#define ADC AVNET_MT3620_SK_ADC_CONTROLLER0

