/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../co2_monitor.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk_rev2.h"

// Button B
#define BUTTON_B AVNET_MT3620_SK_USER_BUTTON_B

// Azure connected LED
#define AZURE_CONNECTED_LED AVNET_MT3620_SK_APP_STATUS_LED_YELLOW

// AVNET Start Kit Definition
#define I2C_ISU2 AVNET_MT3620_SK_ISU2_I2C

// PWM CONTROLLER 0: channel 0 is exposed on CLICK1 (PWM), channel 1 is exposed on: CLICK2 (PWM) and PMOD (Pin 9), channel 2 is exposed on: CLICK1 (INT), CLICK2 (INT) and PMOD (Pin 7).  Pins for this controller are shared with AVNET_MT3620_SK_GPIO0, AVNET_MT3620_SK_GPIO1 and AVNET_MT3620_SK_GPIO2. If this PWM controller is requested, none of these GPIOs can be used.
#define PWM_CLICK_CONTROLLER AVNET_MT3620_SK_PWM_CONTROLLER0

// PWM CONTROLLER 2: channel 0 is used by User LED Red, channel 1 is used by User LED Green, channel 2 is used by User LED Blue. Pins for this controller are shared with AVNET_MT3620_SK_USER_LED_RED, AVNET_MT3620_SK_USER_LED_GREEN, and AVNET_MT3620_SK_USER_LED_BLUE. If this PWM controller is requested, none of these GPIOs can be used.
#define PWM_RGB_CONTROLLER AVNET_MT3620_SK_PWM_CONTROLLER2

