/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// https://docs.microsoft.com/en-us/azure-sphere/app-development/manage-hardware-dependencies
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../azure_sphere_remotex.json.  Do not edit it directly.

#pragma once
#include "mt3620_rdb.h"

// MT3620_RDB_LED1_RED
#define LED1_RED MT3620_RDB_LED1_RED

// LED1_GREEN
#define LED1_GREEN MT3620_RDB_LED1_GREEN

// LED1_GREEN
#define STATUS_LED MT3620_RDB_LED1_GREEN

// LED1_BLUE
#define LED1_BLUE MT3620_RDB_LED1_BLUE

// MT3620_RDB_LED2_RED
#define LED2_RED MT3620_RDB_LED2_RED

// LED2_GREEN
#define LED2_GREEN MT3620_RDB_LED2_GREEN

// LED2_BLUE
#define LED2_BLUE MT3620_RDB_LED2_BLUE

// LED3_RED
#define LED3_RED MT3620_RDB_LED3_RED

// LED3_GREEN
#define LED3_GREEN MT3620_RDB_LED3_GREEN

// LED3_BLUE
#define LED3_BLUE MT3620_RDB_LED3_BLUE

// LED4_RED
#define LED4_RED MT3620_RDB_LED4_RED

// LED4_GREEN
#define LED4_GREEN MT3620_RDB_LED4_GREEN

// LED4_BLUE
#define LED4_BLUE MT3620_RDB_LED4_BLUE

// NETWORKING_LED_GREEN
#define NETWORKING_LED_GREEN MT3620_RDB_NETWORKING_LED_GREEN

// NETWORKING_LED_BLUE
#define NETWORKING_LED_BLUE MT3620_RDB_NETWORKING_LED_BLUE

// BUTTON_A
#define BUTTON_A MT3620_RDB_BUTTON_A

// BUTTON_B
#define BUTTON_B MT3620_RDB_BUTTON_B

// I2C_ISU2
#define I2C_MASTER MT3620_RDB_HEADER4_ISU2_I2C

// SPI_ISU1
#define SPI_MASTER MT3620_RDB_HEADER4_ISU1_SPI

// UART_ISU0
#define UART MT3620_RDB_HEADER2_ISU0_UART

// PWM CONTROLLER 0: channel 0 is exposed on SOCKET1 pin PWM, channel 1 is exposed on: SOCKET2 pin PWM and UART/BLE Connector pin 9, channel 2 is exposed on: SOCKET1 pin INT, SOCKET2 pin INT and UART/BLE Connector pin 7. Pins for this controller are shared with AVNET_MT3620_SK_GPIO0, AVNET_MT3620_SK_GPIO1 and AVNET_MT3620_SK_GPIO2. If this PWM controller is requested, none of these GPIOs can be used.
#define PWM MT3620_RDB_PWM_CONTROLLER0

#define ADC MT3620_RDB_ADC_CONTROLLER0

